server:
    port: 10000
spring:
datasource:
type: com.zaxxer.hikari.HikariDataSource
driver-class-name: com.mysql.jdbc.Driver
url: jdbc:mysql://localhost:3306/graduation-design?useUnicode=true&characterEncoding=utf-8&useSSL=true
username: root
password: root